# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: docker-compose up -d
    - run: npm run job:create-steps
    - run: |
        echo "ENV=dev" >> .env
        echo "PORT=3000"  >> .env
        echo "DB_URL=mongodb://localhost:27017"  >> .env
        echo "DB_DATABASE=teste"  >> .env
        echo "API_VIACEP="  >> .env
        echo "REDIS_URL=redis://localhost" >> .env
    - run: npm run test
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.mailtrap.io
        server_port: 2525
        # user credentials
        username: 1a6a3b83aecf2b
        password: 5854ccc5617e81
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
        to: tiagorosadacost@gmail.com
        # from email name
        from: Github actions
